### PR TITLE
Community info cannot parse to db

### PR DESCRIPTION
**Pull request by Kang-Jack**
Community info cannot parse to db when using get_sell_percommunity(communityname).
may caused by bunch information in data_source cannot be parsed in model.Sellinfo.insert_many(data_source).
use model.Sellinfo.insert instead.

### CODE REVIEW

**Comment by Kang-Jack** [comment]
sorry the scrawl.py file is unexpectedly changed

**Comment by Kang-Jack** [comment]
could you help me revert last 3 commits from pr?

**Comment by XuefengHuang** [comment]
I can't do it because these commits are in your branch

**Comment by Kang-Jack** [comment]
Hoops! I am using browser version, i through it  can during the merge  ,,, let me find another way,,,

**Pull request closed without merging**
